stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: replacetokens@3
      inputs:
        targetFiles: |
          $(Build.SourcesDirectory)/deployment.yaml
          $(Build.SourcesDirectory)/service.yaml
          $(Build.SourcesDirectory)/ingress.yaml
          $(Build.SourcesDirectory)/configmap.yaml
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerConnection'
        repository: 'manoelvsneto/goapi'
        command: 'buildAndPush'
        tags: '$(Build.BuildId)'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'

    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: createSecret
        secretName: $(imagePullSecret)
        dockerRegistryEndpoint: 'DockerConnection'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Report
      inputs:
        artifact: '_goapi'
        publishLocation: 'pipeline'
    
    - task: KubernetesManifest@0
      displayName: Deploy to Kubernetes cluster
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: deploy
        manifests: |
          $(Build.SourcesDirectory)/deployment.yaml
          $(Build.SourcesDirectory)/service.yaml
          $(Build.SourcesDirectory)/ingress.yaml
          $(Build.SourcesDirectory)/configmap.yaml
        imagePullSecrets: |
          $(imagePullSecret)
        containers: 'manoelvsneto/goapi:$(Build.BuildId)'