apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploymentgoapi
  labels:
    app: backendgoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendgoapi
  template:
    metadata:
      labels:
        app: backendgoapi
    spec:
      containers:
        - name:  backendgoapi
          image:  manoelvsneto/goapi
          ports:
            - containerPort: 8080