basePath: /
definitions:
  main.Person:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for a Go CRUD API using SQL Server and Swagger.
  termsOfService: http://swagger.io/terms/
  title: Go CRUD SQL Server Swagger API
  version: "1.0"
paths:
  /people:
    get:
      consumes:
      - application/json
      description: Get all people
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Person'
            type: array
      summary: Get all people
      tags:
      - people
    post:
      consumes:
      - application/json
      description: Create a new person
      parameters:
      - description: Person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/main.Person'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Person'
      summary: Create a new person
      tags:
      - people
  /people/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a person by ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete a person by ID
      tags:
      - people
    get:
      consumes:
      - application/json
      description: Get a person by ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Person'
      summary: Get a person by ID
      tags:
      - people
    put:
      consumes:
      - application/json
      description: Update a person by ID
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/main.Person'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Person'
      summary: Update a person by ID
      tags:
      - people
swagger: "2.0"
